#lane_control/lane_controller_node
#v_bar_old 0.45
v_bar: 0.3
# k_d_old: -12
k_lat: 13.30    #lateral
# k_theta_old: -6.0
k_lon: -5.15    #longitutinal
theta_thres: 0.523
d_thres: 0.2615
d_offset: 0.0

